name: Documentation generation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkout-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build:doc

    - name: Deploy to GitHub Pages 🚀
      uses: Cecilapp/GitHub-Pages-deploy@master
      env:
        EMAIL: fabacrans@gmail.com
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: docs
